name: menofia_military
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  freezed: ^3.0.6
  lottie: ^3.3.1
  json_serializable: ^6.9.5
  firebase_auth: ^5.5.3
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  build_runner: ^2.4.15
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  pretty_qr_code: ^3.4.0
  mobile_scanner: ^6.0.10
  top_snackbar_flutter: ^3.2.0
  awesome_dialog: ^3.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
  assets:
    - assets/images/
    - assets/json/
